### ISSUE TITLE
Version container image releases

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/dockerfiles#30]
In order to prevent breaking consumers projects we should version container image releases.

**Comment by kenoir** [comment]
PInging @alexwlchan for his opinion.

**Comment by alexwlchan** [comment]
Yes.

**Comment by alexwlchan** [comment]
Because Docker images don't have a public API per se, how about simply having an integer version that increments on every new build?

**Comment by alexwlchan** [comment]
This would also mean you could force downstream consumers to pick up a new release.

**Comment by alexwlchan** [comment]
Done in #48.
