### ISSUE TITLE
Fix warning in ECR container pushes

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/dockerfiles#32]
We're getting this warning from the publish-service container:

```
*** Authenticating for `docker push` with ECR
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

Admittedly running in a container adds a level of protection, but that's no reason not to fix the warning and reduce log noise.

**Comment by kenoir** [comment]
Closed as 💀
